image: gradle:4.7.0-jdk8-alpine

stages:
  - build
  - test
  - release

build_package:
  stage: build
  script:
    - ./gradlew build
  artifacts:
    paths:
      - build/
    expire_in: 1 day


run_tests:
  stage: test
  script:
    - echo "No Tests implemented"
    #- run tests ... cd tests


deploy_production:
  stage: release
  variables:
    USERNAME: $PRODUCTION_USERNAME
    PASSWORD: $PRODUCTION_PASSWORD
  script:
    - export VERSION=$(cat VERSION).$CI_PIPELINE_IID
    - ./gradlew publish
  only:
    - /^release.*/
