image: gradle:4.7.0-jdk8-alpine

stages:
  - build
  - test
  - deploy

build_package:
  stage: build
  script:
    - gradle build

run_tests:
  stage: test
  script:
    - gradle build
    #- run tests ... cd tests


deploy_production:
  stage: deploy
  variables:
    USERNAME: $PRODUCTION_USERNAME
    PASSWORD: $PRODUCTION_PASSWORD
  script:
    - gradle build
    - gradle publish
  only:
    - master
